export const testnet7702AgentWalletGuardAbi = [
  {
    type: "function",
    name: "runObservedBatch",
    stateMutability: "nonpayable",
    inputs: [
      { name: "payoutSink", type: "address" },
      { name: "spendAmount", type: "uint256" },
    ],
    outputs: [
      { name: "beforeDip", type: "bool" },
      { name: "duringDip", type: "bool" },
      { name: "afterDip", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "runGuardedBatch",
    stateMutability: "nonpayable",
    inputs: [
      { name: "payoutSink", type: "address" },
      { name: "spendAmount", type: "uint256" },
    ],
    outputs: [
      { name: "allowed", type: "bool" },
      { name: "beforeDip", type: "bool" },
      { name: "duringDip", type: "bool" },
      { name: "afterDip", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "lastMode",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "lastBlocked",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "lastBeforeBalance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "lastDuringBalance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "lastAfterBalance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "lastBeforeDip",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "lastDuringDip",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "lastAfterDip",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "lastTaskSpendAmount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;
